version: '3.1'

services:

  postgres-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres_storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
  
  minio:
      image: minio/minio
      ports:
        - "9000:9000"
        - "9001:9001"
      volumes:
        - minio_storage:/data
      environment:
        MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
        MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      command: server --console-address ":9001" /data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

volumes:
  minio_storage: {}
  postgres_storage: 
    driver: local