apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentimail-backend
spec:
  selector:
    matchLabels:
      app: sentimail-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: sentimail-backend
    spec:
      initContainers:
        - name: init-sentimail-backend
          image: harbor.sentimail.samoth.eu/sentimail/backend:latest
          command: ['sh', 'init.sh']
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sentimail-backend-secret
                  key: secretKey
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: database_name
            - name: DB_HOST
              value: "sentimail-postgres-postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: database_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sentimail-backend-secret
                  key: databasePassword
            - name: MS_METADATA_USER
              value: "ms_metadata"
            - name: MS_METADATA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sentimail-backend-secret
                  key: msMetadataPassword
            - name: MS_CONTENT_USER
              value: "ms_content"
            - name: MS_CONTENT_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: sentimail-backend-secret
                  key: msContentPassword
            - name: MS_ATTACHMENT_USER
              value: "ms_attachment"
            - name: MS_ATTACHMENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sentimail-backend-secret
                  key: msAttachmentPassword
      containers:
      - name: sentimail-backend
        image: harbor.sentimail.samoth.eu/sentimail/backend:latest
        command: ['python', '-m', 'gunicorn', 'sentimail.asgi:application', '-k', 'uvicorn.workers.UvicornWorker', '-b', '0.0.0.0:8000']
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: secretKey
        # - name: DEBUG
        #   value: SNCF
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: allowed_hosts
        - name: CSRF_TRUSTED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: csrf_trusted_origins
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: database_name
        - name: DB_HOST
          value: "sentimail-postgres-postgresql"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: database_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: databasePassword
        - name: MINIO_ENDPOINT
          value: "sentimail-minio:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: minio_access_key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: minioSecretKey
        - name: MINIO_BUCKET
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: minio_bucket
        - name: RABBITMQ_HOST
          value: "sentimail-rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: rabbitmq_user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: rabbitmqPassword
        - name: RABBITMQ_QUEUE
          value: "sentimail"
        - name: RABBITMQ_VHOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: rabbitmq_vhost
        - name: MS_METADATA_USER
          value: "ms_metadata"
        - name: MS_METADATA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: msMetadataPassword
        - name: MS_CONTENT_USER
          value: "ms_content"
        - name: MS_CONTENT_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: msContentPassword
        - name: MS_ATTACHMENT_USER
          value: "ms_attachment"
        - name: MS_ATTACHMENT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: msAttachmentPassword
        resources:
          requests:
            cpu: '100m'
            memory: '128M'
          limits:
            cpu: '1'
            memory: 1024M
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: sentimail-backend-service
spec:
  selector:
    app: sentimail-backend
  ports:
  - port: 8000