apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend.yml
- frontend.yml
- ms-metadata.yml
- ms-content.yml
- ms-attachment.yml
- ingressRoute.yml
namespace: sentimail-dev
patches:
- target:
    group: traefik.containo.us
    version: v1alpha1
    kind: IngressRoute
    name: sentimail-ingressroute
  patch: |-
    - op: replace
      path: /spec/routes/0/middlewares/0/namespace
      value: sentimail-prod
    - op: replace
      path: /spec/routes/0/services/0/namespace
      value: sentimail-prod
    - op: replace
      path: /spec/routes/1/middlewares/0/namespace
      value: sentimail-prod
    - op: replace
      path: /spec/routes/1/services/0/namespace
      value: sentimail-prod