apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentimail-ms-attachment
spec:
  selector:
    matchLabels:
      app: sentimail-ms-attachment
  replicas: 1
  template:
    metadata:
      labels:
        app: sentimail-ms-attachment
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: sentimail-ms-attachment
        image: harbor.sentimail.samoth.eu/sentimail/ms-attachment:latest
        env:
        - name: BACKEND_HOST
          value: "sentimail-backend-service:8000"
        - name: RABBITMQ_HOST
          value: "sentimail-rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "sentimail-dev"
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: rabbitmqPassword
        - name: RABBITMQ_QUEUE
          value: "sentimail"
        - name: RABBITMQ_VHOST
          value: "/sentimail-dev"
        - name: MINIO_ENDPOINT
          value: "sentimail-minio:9000"
        - name: MINIO_ACCESS_KEY
          value: "sentimail-dev"
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: minioSecretKey
        - name: MINIO_BUCKET
          value: "sentimail-dev"
        - name: MS_ATTACHMENT_USER
          value: "ms_attachment"
        - name: MS_ATTACHMENT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: msAttachmentPassword
        - name: VIRUS_TOTAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: virustotalApiKey
        resources:
          requests:
            cpu: '10m'
            memory: '64M'
          limits:
            cpu: '1'
            memory: 1024M
      