apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentimail-language-tool
spec:
  selector:
    matchLabels:
      app: sentimail-language-tool
  replicas: 1
  template:
    metadata:
      labels:
        app: sentimail-language-tool
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: sentimail-language-tool
        image: erikvl87/languagetool
        ports:
        - containerPort: 8010
        resources:
          requests:
            cpu: '10m'
            memory: '64M'
          limits:
            cpu: '500m'
            memory: 1024M
---
apiVersion: v1
kind: Service
metadata:
  name: sentimail-language-tool-service
spec:
  selector:
    app: sentimail-language-tool
  ports:
  - port: 8010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentimail-ms-content
spec:
  selector:
    matchLabels:
      app: sentimail-ms-content
  replicas: 1
  template:
    metadata:
      labels:
        app: sentimail-ms-content
    spec:
      volumes:
      - name: ms-content-data
        persistentVolumeClaim:
          claimName: ms-content-data-pvc
      imagePullSecrets:
      - name: regcred
      initContainers:
      - name: volume-permissions
        image: busybox:latest
        command: ["sh", "-c", "chmod 700 /ms-content; chown -R 65532:65532 /ms-content"]
        volumeMounts:
        - mountPath: /ms-content
          name: ms-content-data
      containers:
      - name: sentimail-ms-content
        image: harbor.sentimail.samoth.eu/sentimail/ms-content:latest
        env:
        - name: BACKEND_HOST
          value: "sentimail-backend-service:8000"
        - name: RABBITMQ_HOST
          value: "sentimail-rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: rabbitmq_user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: rabbitmqPassword
        - name: RABBITMQ_QUEUE
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: rabbitmq_queue
        - name: RABBITMQ_VHOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: rabbitmq_vhost
        - name: MINIO_ENDPOINT
          value: "sentimail-minio:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: minio_access_key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: minioSecretKey
        - name: MINIO_BUCKET
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: minio_bucket
        - name: MS_CONTENT_USER
          value: "ms_content"
        - name: MS_CONTENT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: msContentPassword
        - name: GOOGLE_SAFE_BROWSING_API_KEY
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: googleSafeBrowsingApiKey
        - name: LANGUAGETOOL_HOST
          value: "http://sentimail-language-tool-service:8010"
        resources:
          requests:
            cpu: '10m'
            memory: '64M'
          limits:
            cpu: '1'
            memory: 1024M
        volumeMounts:
        - mountPath: /ms-content
          name: ms-content-data