apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentimail-language-tool
spec:
  selector:
    matchLabels:
      app: sentimail-language-tool
  replicas: 1
  template:
    metadata:
      labels:
        app: sentimail-language-tool
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: sentimail-language-tool
        image: erikvl87/languagetool
        ports:
        - containerPort: 8010
        resources:
          requests:
            cpu: '10m'
            memory: '64M'
          limits:
            cpu: '500m'
            memory: 1024M
---
apiVersion: v1
kind: Service
metadata:
  name: sentimail-language-tool-service
spec:
  selector:
    app: sentimail-language-tool
  ports:
  - port: 8010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentimail-ms-content
spec:
  selector:
    matchLabels:
      app: sentimail-ms-content
  replicas: 1
  template:
    metadata:
      labels:
        app: sentimail-ms-content
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: sentimail-ms-content
        image: harbor.sentimail.samoth.eu/sentimail/ms-content:latest
        env:
        - name: BACKEND_HOST
          value: "sentimail-backend-service:8000"
        - name: RABBITMQ_HOST
          value: "sentimail-rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "sentimail-dev"
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: rabbitmqPassword
        - name: RABBITMQ_QUEUE
          value: "sentimail"
        - name: RABBITMQ_VHOST
          value: "/sentimail-dev"
        - name: MINIO_ENDPOINT
          value: "sentimail-minio:9000"
        - name: MINIO_ACCESS_KEY
          value: "sentimail-dev"
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: minioSecretKey
        - name: MINIO_BUCKET
          value: "sentimail-dev"
        - name: MS_CONTENT_USER
          value: "ms_content"
        - name: MS_CONTENT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: msContentPassword
        - name: GOOGLE_SAFE_BROWSING_API_KEY
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: googleSafeBrowsingApiKey
        - name: LANGUAGETOOL_HOST
          value: "http://sentimail-language-tool-service:8010"
        resources:
          requests:
            cpu: '10m'
            memory: '64M'
          limits:
            cpu: '1'
            memory: 1024M
