apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentimail-ms-metadata
spec:
  selector:
    matchLabels:
      app: sentimail-ms-metadata
  replicas: 1
  template:
    metadata:
      labels:
        app: sentimail-ms-metadata
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: sentimail-ms-metadata
        image: harbor.sentimail.samoth.eu/sentimail/ms-metadata:latest
        env:
        - name: BACKEND_HOST
          value: "sentimail-backend-service:8000"
        - name: RABBITMQ_HOST
          value: "sentimail-rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: rabbitmq_user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: rabbitmqPassword
        - name: RABBITMQ_QUEUE
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: rabbitmq_queue
        - name: RABBITMQ_VHOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: rabbitmq_vhost
        - name: MINIO_ENDPOINT
          value: "sentimail-minio:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: minio_access_key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: minioSecretKey
        - name: MINIO_BUCKET
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: minio_bucket
        - name: MS_METADATA_USER
          value: "ms_metadata"
        - name: MS_METADATA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: msMetadataPassword
        - name: SPAMCHECKER_API_KEY
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: spamcheckerApiKey
        - name: GREYNOISE_KEY
          valueFrom:
            secretKeyRef:
              name: sentimail-backend-secret
              key: greynoiseKey
        resources:
          requests:
            cpu: '10m'
            memory: '64M'
          limits:
            cpu: '1'
            memory: 1024M
      