apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-content-data
  namespace: sentimail-dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: ms-content-pv
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ms-content-pv
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce 