apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-content-data
  namespace: sentimail-dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: ms-content-data
  resources:
    requests:
      storage: 128Mi