global:
  postgresql:
    auth:
      username: "sentimail-prod"
      database: "sentimail-prod"
      existingSecret: "postgres-secret"
      secretKeys:
        adminPasswordKey: "admin-password"
        userPasswordKey: "user-password"
persistance:
  size: 5Gi