apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-minio
  namespace: sentimail-dev

spec:
  rules:
    - host: minio.sentimail.samoth.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  sentimail-minio
                port:
                  number: 9001