# Default values for sentimail.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

postgresql:
  global:
    postgresql:
      auth:
        username: "sentimail-dev"
        database: "sentimail-dev"
        existingSecret: "postgres-secret"
        secretKeys:
          adminPasswordKey: "admin-password"
          userPasswordKey: "user-password"
  persistance:
    size: 5Gi

rabbitmq:
  auth:
    username: admin
    existingPasswordSecret: rabbitmq-secret

minio:
  persistance:
    size: 5Gi