# Generated by Django 4.2.7 on 2023-11-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='name',
            new_name='hash',
        ),
        migrations.AddField(
            model_name='email',
            name='user',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
