# Generated by Django 4.2.7 on 2023-11-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_uploadfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='hash',
            new_name='uuid',
        ),
    ]
