# Generated by Django 4.2.7 on 2023-11-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_uploadfile_data_alter_email_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='uuid',
            field=models.CharField(max_length=100),
        ),
    ]
