# Generated by Django 4.2.7 on 2023-12-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_data_uploadfile_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='id',
        ),
        migrations.AlterField(
            model_name='email',
            name='uuid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
