# Generated by Django 4.2.7 on 2023-12-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_email_id_alter_email_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='isReady',
            field=models.BooleanField(default=False),
        ),
    ]
