# Generated by Django 4.2.7 on 2023-12-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_email_isready'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='responseMetadataDomain',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='email',
            name='responseMetadataIp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
