# Generated by Django 4.2.7 on 2023-12-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_email_responsemetadatadomain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='username',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
