# Generated by Django 4.2.7 on 2023-12-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_email_responsemetadataspf'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='responseContentKeywords',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='email',
            name='responseContentLinks',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='email',
            name='responseContentSpelling',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='email',
            name='responseContentTyposquatting',
            field=models.CharField(default='', max_length=100),
        ),
    ]
