# Generated by Django 4.2.7 on 2024-01-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_email_responsecontentcharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='responseAttachmentFiletype',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='email',
            name='responseAttachmentHash',
            field=models.CharField(default='', max_length=100),
        ),
    ]
