# Generated by Django 4.2.7 on 2024-01-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_email_responseattachmentfiletype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
