# Generated by Django 4.2.7 on 2024-01-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_email_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='recipient',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='email',
            name='sender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='email',
            name='verdict',
            field=models.CharField(default='', max_length=100),
        ),
    ]
