name: The CI
on:
  push:

jobs:
  Explore-GitHub-Actions:
    runs-on: sentimail-runner
    container:
      image: gcr.io/kaniko-project/executor:latest
    steps:
      - name: where tf ami ?
        run: pwd
      - name: what do I have around me ?
        run: ls -la