name: The CI
on:
  push:
    branches: [ "dev" ]

jobs:
  Build-Backend-Image:
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Docker login
        uses: docker/login-action@v3
        with:
            registry: harbor.sentimail.samoth.eu
            username: ${{ secrets.HARBOR_USERNAME }}
            password: ${{ secrets.HARBOR_PASSWORD }}
      - 
        name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: backend/sentimail
          push: true
          tags: Sentimail/Backend:latest
      - 
        name: Build and push ms-metadata
        uses: docker/build-push-action@v5
        with:
          context: ms-metadata
          push: true
          tags: Sentimail/ms-metadata:latest