name: The CI
on:
  push:
    branches: [ "dev" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    
jobs:
  BuildImages:
    runs-on: ubuntu-latest
    outputs:
      image_id_backend: ${{ steps.img-backend.outputs.imageid }}
      image_id_ms_metadata: ${{ steps.img-ms-metadata.outputs.imageid }}
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Docker login
        uses: docker/login-action@v3
        with:
            registry: harbor.sentimail.samoth.eu
            username: ${{ secrets.HARBOR_USERNAME }}
            password: ${{ secrets.HARBOR_PASSWORD }}
      - 
        id: img-backend
        name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: backend/sentimail
          push: true
          tags: harbor.sentimail.samoth.eu/sentimail/backend:latest
      - 
        id: img-ms-metadata
        name: Build and push ms-metadata
        uses: docker/build-push-action@v5
        with:
          context: ms-metadata
          push: true
          tags: harbor.sentimail.samoth.eu/sentimail/ms-metadata:latest
  Deploy:
    runs-on: ubuntu-latest
    needs: BuildImages
    defaults:
      run:
        shell: bash
        working-directory: ./ansible
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      -
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - 
        name: Install dependencies
        run: python -m pip install --upgrade pip ansible-core kubernetes PyYAML jsonpatch
      -
        name: Install ansible deps
        run: ansible-galaxy collection install kubernetes.core
      - 
        name: Write ca cert file
        run: echo -n $K8S_CACERT | base64 -d > $RUNNER_TEMP/.K8S_CACERT
        env:
          K8S_CACERT: ${{ secrets.K8S_CACERT }}
          RUNNER_TEMP: ${{ runner.temp }}
      -
        name: Deploy
        run: ansible-playbook deploy_pb.yml
        env:
          K8S_AUTH_SSL_CA_CERT: ${{ runner.temp }}/.K8S_CACERT
          K8S_AUTH_API_KEY: ${{ secrets.K8S_AUTH_API_KEY }}
          K8S_AUTH_HOST: ${{ vars.K8S_AUTH_HOST }}
          SENTIMAIL_BACKEND_IMAGE_ID: ${{ needs.BuildImages.outputs.image_id_backend }}
          SENTIMAIL_MS_METADATA_IMAGE_ID: ${{ needs.BuildImages.outputs.image_id_backend }}